apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: myapp
build:
  artifacts:
    - image: service_a
      context: ./service_a
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: /app
    - image: service_b
      context: ./service_b
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: /app

deploy:
  kubectl:
    manifests:
      - k8s/service_a.yml
      - k8s/service_b.yml
      - k8s/rate-limit-service-a.yml
      - k8s/rate-limit-service-b.yml
      - k8s/api-key-service-a.yml
      - k8s/api-key-service-b.yml
      - k8s/api-consumer.yml
      - k8s/ingress.yml
      - k8s/opa-bundle-server.yml
      # - k8s/opa-server.yml
      # - k8s/opa-plugin.yml
