apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: myapp
build:
  artifacts:
    - image: service_a
      context: ./service_a
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: /app
    - image: service_b
      context: ./service_b
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: /app

deploy:
  kubectl:
    manifests:
      # Applications
      - k8s/applications/service-a/service_a.yml
      - k8s/applications/service-b/service_b.yml
      # Policies
      - k8s/policies/rate-limit/rate-limit-service-a.yml
      - k8s/policies/rate-limit/rate-limit-service-b.yml
      - k8s/policies/api-key/api-key-service-a.yml
      - k8s/policies/api-key/api-key-service-b.yml
      - k8s/policies/opa-plugin.yml
      # Networking
      - k8s/networking/api-consumer.yml
      - k8s/networking/ingress.yml
      # Platform Services
      - k8s/platform/postgres/postgres-secret.yml
      - k8s/platform/postgres/postgres-pvc.yml
      - k8s/platform/postgres/postgres-deployment.yml
      # - k8s/platform/opa/opa-bundle-server.yml
      # - k8s/platform/opa/opa-server.yml
